services:
  nginx:
    image: nginx:stable
    depends_on: [frontend, api, runner]
    ports: ["8080:80"]   # открываем http://localhost:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    working_dir: /etc/nginx
    restart: unless-stopped

  docker:
    image: docker:24-dind
    privileged: true
    command:
      - --host=tcp://0.0.0.0:2375
      - --host=unix:///var/run/docker.sock
    environment:
      - DOCKER_TLS_CERTDIR=
    volumes:
      - dind-data:/var/lib/docker
      - nfwork:/nfwork  # <-- общий том с runner
    healthcheck:
      test: [ "CMD", "docker", "info" ]
      interval: 5s
      timeout: 5s
      retries: 30
      start_period: 5s
    restart: unless-stopped


  frontend:
    build: ../../frontend
    restart: unless-stopped


  api:
    build: ../../api
    environment:
      - RUNNER_BASE=http://nginx/runner
      - DATABASE_URL=postgresql+psycopg://app:app@postgres:5432/app
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=miniokey
      - S3_SECRET_KEY=miniopass
      - S3_BUCKET_DATASETS=datasets
      - JWT_SECRET=change-me-in-prod
      - ADMIN_USER=admin
      - ADMIN_PASS=admin123
    restart: unless-stopped

  runner:
    build: ../../runner
    environment:
      - WORK_DIR=/work
      - DOCKER_HOST=tcp://docker:2375
      - S3_ENDPOINT=http://minio:9000
      - S3_ACCESS_KEY=miniokey
      - S3_SECRET_KEY=miniopass
      - S3_BUCKET_RUNS=runs
    depends_on:
      docker:
        condition: service_healthy
    volumes:
      - nfwork:/work
      - nfcore-cache:/opt/nfcore_cache
    restart: unless-stopped


  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped


  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=miniokey
      - MINIO_ROOT_PASSWORD=miniopass
    ports: ["9001:9001"]   # веб-консоль MinIO (по желанию)
    volumes:
      - minio-data:/data
    restart: unless-stopped


  redis:
    image: redis:7
    restart: unless-stopped

volumes:
  pgdata: {}
  minio-data: {}
  dind-data: {}
  nfwork: {}
  nfcore-cache: {}